checking waittime out after deployment and test url

diff --git a/.github/workflows/azure-staticwebapp.yml b/.github/workflows/azure-staticwebapp.yml
--- a/.github/workflows/azure-staticwebapp.yml
+++ b/.github/workflows/azure-staticwebapp.yml
@@ -67,6 +67,26 @@ jobs:
           app_location: ${{ env.APP_ARTIFACT_LOCATION }}
           ###### End of Repository/Build Configurations ######
           output_location: ${{ env.APP_ARTIFACT_LOCATION }}
+  verify_http_status_job:
+    needs: build_and_deploy_job
+    permissions:
+      contents: none
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
+    runs-on: ubuntu-latest
+    name: Verify HTTP Status Job
+    steps:
+      - name:  Wait for 30 seconds
+        run: sleep 30
+      - name:  verify http status
+        run: |
+          echo "Verifying the HTTP status of the static web app"
+          curl -I https://www.pkchai.com | grep HTTP
+          if [ $? -ne 0 ]; then
+            echo "Failed to verify HTTP status"
+            exit 1
+          else
+            echo "HTTP status verified successfully"
+          fi
   close_pull_request_job:
     permissions:
       contents: none
